// Fill out your copyright notice in the Description page of Project Settings.


#include "Item/TFItemBox.h"
#include "Components/BoxComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Particles/ParticleSystemComponent.h"
#include "Physics/TFCollision.h"
#include "Interface/TFCharacterItemInterface.h"


// Sets default values
ATFItemBox::ATFItemBox()
{
	Trigger = CreateDefaultSubobject<UBoxComponent>(TEXT("TriggetBox"));
	Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	Effect = CreateDefaultSubobject<UParticleSystemComponent>(TEXT("Effect"));
	//CreateDefaultSubobjectИІ НЧЧрЧЯПЉ РЇ ММАЁСі ЦїРЮХЭПЁ ДыЧб АДУМ Л§МК


	RootComponent = Trigger;
	Mesh->SetupAttachment(Trigger);
	Effect->SetupAttachment(Trigger);

	Trigger->SetCollisionProfileName(CPROFILE_ABTRIGGER);
	Trigger->SetBoxExtent(FVector(40.0f, 42.0f, 30.0f));
	Trigger->OnComponentBeginOverlap.AddDynamic(this, &ATFItemBox::OnOverlapBegin);
	//ЦЎИЎАХРЧ АцПь ПьИЎАЁ ОеМ­ МГСЄЧпДј ЦЎИЎАХПЕ РќПы ФнИЎРќ ЧСЗЮЧЪ ЛчПы
	//OnComponentBeginOverlapРК КэЗчЧСИАЦЎПЁМ­ЕЕ ЛчПыАЁДЩЧЯЕЕЗЯ ДйРЬГЊЙЭ ЕЈИЎАдРЬЦЎЗЮ МГСЄРЬ ЕЧОю РжДй.
	//ЕћЖѓМ­ ПьИЎАЁ ПЌАсЧЯДТ ЧдМіРЧ АцПьПЁДТ UFUNCTIONРИЗЮ СіСЄРЛ ЧиСрОп ЧбДй.

	/*Mesh Component МГСЄ*/
	static ConstructorHelpers::FObjectFinder<UStaticMesh> BoxMeshRef(TEXT("/Script/Engine.StaticMesh'/Game/Cave_Ruins/Meshes/SM_Dungeon_chest.SM_Dungeon_chest'"));
	if (BoxMeshRef.Object)
	{
		Mesh->SetStaticMesh(BoxMeshRef.Object);
	}
	Mesh->SetRelativeLocation(FVector(0.0f, -3.5f, -30.0f));
	Mesh->SetCollisionProfileName(TEXT("NoCollision")); //ЛѓРкДТ КИПЉСжБтИИ ЧЯАэ УцЕЙРЬ РЯОюГЊСі ОЪЕЕЗЯ NoCollision ЧСЗЮЧЪ СіСЄ

	static ConstructorHelpers::FObjectFinder<UParticleSystem> EffectRef(TEXT("/Script/Engine.ParticleSystem'/Game/Realistic_Starter_VFX_Pack_Vol2/Particles/Destruction/P_Destruction_Building_A.P_Destruction_Building_A'"));
	if (EffectRef.Object)
	{
		Effect->SetTemplate(EffectRef.Object);
		//SetTemplateРЛ ХыЧи  EffectRef.Object СіСЄ
		Effect->bAutoActivate = false;
		//УГРНПЁ ЙйЗЮ ЙпЕПЕЧСі ОЪЕЕЗЯ bAutoActivate=falseЗЮ ЧЯПЉ КёШАМКШ­
	}

}

void ATFItemBox::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepHitResult)
{
	if (nullptr == Item)
	{
		Destroy();
		return;
	}

	ITFCharacterItemInterface* OverlappingPawn = Cast< ITFCharacterItemInterface>(OtherActor); //ПЉБтМ­ OtherActorАЁ ФГИЏХЭРЮЕЅ  ITFCharacterItemInterfaceИІ ЛѓМгЙоОвРН.
	//КЮЕњФЃ ОзХЭПЁ ДыЧиМ­ ЧќКЏШЏ СјЧр
	if (OverlappingPawn)
	{
		OverlappingPawn->TakeItem(Item);
	}

	Effect->Activate(true);
	Mesh->SetHiddenInGame(true);
	SetActorEnableCollision(false);
	Effect->OnSystemFinished.AddDynamic(this, &ATFItemBox::OnEffectFinished);

	/*ОЦРЬХл НРЕц
	* ПьИЎАЁ ОЦРЬХлРЛ НРЕц ЧпРЛ ЖЇ ФГИЏХЭЗЮКЮХЭ ОЦРЬХлРЛ НРЕцЧпДйАэ РќДоЧв Мі РжДТ РЮХЭЦфРЬНКИІ ЧЯГЊ УпАЁЧЯРк.
	* ОЦРЬХлРК ЙЬЕщПўОюАэ ФГИЏХЭДТ АдРг ЗЙРЬОюРЬБт ЖЇЙЎПЁ ПьИЎАЁ РЮХЭЦфРЬНКИІ ХыЧиМ­ АЃСЂРћРИЗЮ ШЃУтЧиСрОп ЧбДй.
	*/
}

void ATFItemBox::OnEffectFinished(UParticleSystemComponent* ParticleSystem)
{
	Destroy();
}


